### ISSUE TITLE
Tsid warnings at the validation step from the LiPD utilities

### ISSUE THREAD

**Issue by khider** [nickmckay/LiPD-utilities#10]
Tsids error when using lipd.validate() but Tsids are being generated nonetheless
[ODP659.Tiedemann.1994.zip](https://github.com/nickmckay/LiPD-utilities/files/1065321/ODP659.Tiedemann.1994.zip)
[ODP659.Tiedemann.1994.xlsx](https://github.com/nickmckay/LiPD-utilities/files/1065322/ODP659.Tiedemann.1994.xlsx)

**Comment by chrismheiser** [comment]
Not reproducible 
<img width="674" alt="screen shot 2017-06-12 at 1 42 15 pm" src="https://user-images.githubusercontent.com/8582482/27054200-fd0dfeda-4f74-11e7-84cd-bc2853d18bb1.png">
<img width="1253" alt="screen shot 2017-06-12 at 1 42 07 pm" src="https://user-images.githubusercontent.com/8582482/27054201-fd2be7a6-4f74-11e7-9b97-effef3790e52.png">

**Comment by chrismheiser** [comment]
[Kawahata.2009.zip](https://github.com/nickmckay/LiPD-utilities/files/1079184/Kawahata.2009.zip)

I created a file through Excel -> LiPD that gave me the error. 
File has TSids in JSON. 
`                  { 
                    "TSid" : "PYTKXWTD3OW",
                    "TakenAtDepth" : "Depth",
                    "number" : 1,
                    "variableName" : "sample type"
                  },
                  { 
                    "TSid" : "PYTGN31D2ND",
                    "TakenAtDepth" : "Depth",
                    "number" : 2,
                    "variableName" : "specific name"
                  },
                  { 
                    "TSid" : "PYTIEZNZ4IP",
                    "TakenAtDepth" : "Depth",
                    "number" : 3,
                    "variableName" : "sample #"
                  },`


Validator API shows missing 109 TSids

<img width="603" alt="screen shot 2017-06-15 at 3 38 49 pm" src="https://user-images.githubusercontent.com/8582482/27204579-d960deee-51e0-11e7-8339-56124f188f76.png">

Same file passes without the TSid warning on the website. 


<img width="556" alt="screen shot 2017-06-15 at 3 40 26 pm" src="https://user-images.githubusercontent.com/8582482/27204617-ff472578-51e0-11e7-8b00-1670018e9001.png">

**Comment by chrismheiser** [comment]
The issue is still elusive. I did the same steps as earlier and the warning no longer shows up. It seems like it triggers for the first validation of some files, but not again. 

- Convert Excel file -> validate -> No TSid warnings
- Using the same file that caused the issue in the post above -> validate - > No TSid warnings

**Comment by khider** [comment]
Got the warning again. Screenshot and file attached
![screen shot 2017-06-19 at 4 41 49 pm](https://user-images.githubusercontent.com/11758571/27310330-50f2122c-550e-11e7-9950-533c52fa15f3.png)
[GeoB1023-5.Kim.2002.xlsx](https://github.com/nickmckay/LiPD-utilities/files/1086593/GeoB1023-5.Kim.2002.xlsx)

**Comment by chrismheiser** [comment]
I found what may be the issue. It's a sneaky one. I'll note the reasoning to make it known here in the issue tracker. 

The process of converting an excel file into a LiPD file is: 

1. Parse and convert the excel data
2. Write a LiPD file (using "manual" steps in the excel_main.py, NOT writeLipd()... )
3. readLipd() - Read the LiPD file back into the workspace. (to gain the benefits of inferred calculations, structure updates, etc)

<< User validates file before TSids are added in step 4 >>

4. writeLipd() - This is where TSids are created and stored in the LiPD file

The issue is between steps 3 and 4. The reason the bug only happens on the first validation is because that's the only time that the LiPD data in the workspace does not have TSids. If you were to restart the Python console and load in that LiPD file again, that would be the file that had TSids, and you wouldn't get the validation warning again.
