### ISSUE TITLE
Python: Library separate from application?

### ISSUE THREAD

**Issue by brews** [nickmckay/LiPD-utilities#39]
Is it possible for a general developer-oriented LiPD library to be packaged separately from end-user-oriented LiPD utilities and applications?

I may have use for LiPD within a much larger analysis system. It would be nice to have a library or framework to write project-specific applications that read/write/parse lipid files as a standardized object.

**Comment by nickmckay** [comment]
Hey Brewster.  I guess I'm not sure what you're asking for. The utilities here include both the developer functionality, and the user-oriented stuff that's overlain, although @chrismheiser knows much more about the details in Python. It's possible/likely that what you're looking for is here, but just not obvious or documented. If it would be helpful, I'd be happy to have a quick skype call with you and @chrismheiser to figure out what you're trying to do and how we can help.

**Comment by chrismheiser** [comment]
If I'm understanding right, you should be able to include a LiPD package dependency into whatever you're doing, through PyPi or manually, and use whichever functions you please. We used to have some automated prompts and such overlaying the functions/package, but that's not longer the case. 

I'm not sure if you've seen these docs yet, but they're a bit more in depth than the core repository for the overall LiPD Utilities

http://nickmckay.github.io/LiPD-utilities/python/index.html

**Comment by CommonClimate** [comment]
@brews this is exactly the feedback that we need, and I agree that the log files are a pain in the neck. They are debug features, I get it, but I wish they could be be exported only if a `--debug` option is turned on (or something like that). An alternative would be to call them .lipd_debug and .lipd_benchmark, so they are less visible.

In any case, one of the persistent design problems of lipd and associated libraries (e.g. pyleoclim) is that we expect to serve basic users with virtually no programming background, vs power users like yourself. I am strongly of the opinion that the library should serve power users (which includes documentation!), but be ergonomic enough that the most essential commands (e.g. readLipd) have intuitive default behavior. We're pretty close to it, I think, except for this business of log files and managing the input directory, which was there to support non power-users.

**Comment by chrismheiser** [comment]
Any other direct suggestions on what needs to change to make this more useful?

I've moved the logs to only start from lipd.debug(), instead of automatically.

The only other things I see as problematic are the global variables, which are 

`_timeseries_data = {}`
`_settings = {"note_update": True, "note_validate": True, "verbose": True, "debug": False}`
`_logs = {"start": None, "benchmark": None}`
`_cwd = os.getcwd()`
`_files = {".txt": [], ".lpd": [], ".xls": []}`


timeseries data is a definite weak point, but there's not really any better way to handle that except for global storage. 
_settings, _logs, can be moved to an "options" parameter on each function, putting it on the user to decide what they want. 
_cwd I believe was something that deborah wanted in Spyder, but doesn't serve a whole lot of purpose.
_files is another convenience variable that can be worked around. It was added in to make managing multiple files and file types in the workspace easier, but can be done in individual read functions.

**Comment by chrismheiser** [comment]
@brews 

http://nickmckay.github.io/LiPD-utilities/python/source/lipd.html#module-lipd

Not sure if you saw this piece of the docs. The Sphinx module generated the pages a little strange, so these main functions are hard to find. I'll try to sort out the pages to be easier to browse and update the docs too.

**Comment by brews** [comment]
Thanks @chrismheiser. No other concrete changes at the moment, so I'll close this issue. I'll be sure to open another issue if I can come across something else specific.

Thanks again!
